#!/usr/bin/env python3
import argparse
import traceback

import jsnapshot_core

parser = argparse.ArgumentParser(prog="jsnapshot-create", description="Create new system snapshot")
parser.add_argument("--info", default="", required=False, type=str, help="User comment for snapshot")
args, leftovers = parser.parse_known_args()

callback = jsnapshot_core.AppCallback()
result = jsnapshot_core.initialize_app(callback)
if not result:
    callback.error("App init failed")
    raise SystemExit(1)

volume = jsnapshot_core.bind_root()
engine = jsnapshot_core.BackupEngine(callback, volume)
try:
    engine.create_snapshot(info=args.info)
except Exception:
    traceback.print_exc()
    callback.error("Operation failed.")
    raise SystemExit(1)
