#!/usr/bin/env python3
import argparse
from jsnapshot_core.callback import AppCallback
from jsnapshot_core.engine import BackupEngine
from jsnapshot_core.initializer import initialize_app
import jsnapshot_core

parser = argparse.ArgumentParser(prog="jsnapshot-delete", description="Delete one snapshot.")
parser.add_argument("snapshots", nargs="+", type=str, help="Snapshot name")
args = parser.parse_args()
items = args.snapshots

callback = AppCallback()
result = initialize_app(callback)
if not result:
    raise SystemExit(1)

volume = jsnapshot_core.bind_root()
engine = BackupEngine(callback, volume)
snapshots = engine.list_snapshots()

for name in items:
    target = None
    for volume in snapshots:
        if volume.name == name:
            target = volume

    if target is None:
        callback.warn("Snapshot with name " + name + " not found")
        continue

    if target.is_booted():
        callback.error("Can't delete this snapshot: You're booted inside them. " +
                       "Maybe you recovered some snapshot and \n  " +
                       "trying to delete auto-created backup. Reboot system and try again.")
        continue

    callback.notice("Deleting snapshot " + target.path)
    target.delete()
