#!/usr/bin/env python3
import argparse
import traceback
import jsnapshot_core

from jsnapshot_core.callback import AppCallback
from jsnapshot_core.engine import BackupEngine
from jsnapshot_core.initializer import initialize_app

parser = argparse.ArgumentParser(prog="jsnapshot-create", description="Create new system snapshot")
parser.add_argument("--info", default="", required=False, type=str, help="User comment for snapshot")
args, leftovers = parser.parse_known_args()

callback = AppCallback()
result = initialize_app(callback)
if not result:
    callback.error("App init failed")
    raise SystemExit(1)

volume = jsnapshot_core.bind_root()
engine = BackupEngine(callback, volume)
try:
    engine.create_snapshot(tag_user=True, info=args.info)
except Exception:
    traceback.print_exc()
    callback.error("Operation failed.")
    raise SystemExit(1)
