#!/usr/bin/env python3
import argparse
import jsnapshot_core
from jsnapshot_core.callback import AppCallback
from jsnapshot_core.engine import BackupEngine
from jsnapshot_core.initializer import initialize_app

parser = argparse.ArgumentParser(prog="jsnapshot-delete", description="Edit snapshot properties.")
parser.add_argument("--info", type=str, help="Set snapshot info", required=False)
parser.add_argument("snapshot", type=str, help="Snapshot name")
args, a = parser.parse_known_args()
name = args.snapshot

callback = AppCallback()
result = initialize_app(callback)
if not result:
    raise SystemExit(1)

volume = jsnapshot_core.bind_root()
engine = BackupEngine(callback, volume)
snapshots = engine.list_snapshots()

target = None
for volume in snapshots:
    if volume.name == name:
        target = volume

if target is None:
    callback.warn("Snapshot with name " + name + " not found")
    raise SystemExit(1)

if args.info is not None:
    target.metadata["info"] = args.info

target.save_metadata()
