#!/usr/bin/env python3
import argparse
import jsnapshot_core

parser = argparse.ArgumentParser(prog="jsnapshot-delete", description="Delete one snapshot.")
parser.add_argument("snapshot", type=str, help="Snapshot name")
args = parser.parse_args()
name = args.snapshot

callback = jsnapshot_core.AppCallback()
result = jsnapshot_core.initialize_app(callback)
if not result:
    callback.error("App init failed")
    raise SystemExit(1)

volume = jsnapshot_core.bind_root()
engine = jsnapshot_core.BackupEngine(callback, volume)
snapshots = engine.list_snapshots()

item = None
for a in snapshots:
    if a.name == name:
        item = a

if item is None:
    callback.warn("Snapshot with name " + name + " not found")
    raise SystemExit(1)

callback.notice("Deleting snapshot " + item.path)
item.delete()
